services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cyper-db
    ports:
      - "5432:5432"