services:
  backend:
    build:
      context: ./backend
    image: khalid7730/intrusion-api:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_MODEL_KEY: ${AWS_MODEL_KEY}
      AWS_LOCAL_MODEL_PATH: ${AWS_LOCAL_MODEL_PATH}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_SSL: ${REDIS_SSL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}

  worker:
    image: khalid7730/intrusion-api:latest
    command: python -m app.rabbitmq.worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_MODEL_KEY: ${AWS_MODEL_KEY}
      AWS_LOCAL_MODEL_PATH: ${AWS_LOCAL_MODEL_PATH}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_SSL: ${REDIS_SSL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      

