"""initial

Revision ID: dda7c246c097
Revises: 
Create Date: 2026-06-30 13:17:17.079227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda7c246c097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dur', sa.Float(), nullable=True),
    sa.Column('proto', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('spkts', sa.Integer(), nullable=True),
    sa.Column('dpkts', sa.Integer(), nullable=True),
    sa.Column('sbytes', sa.Integer(), nullable=True),
    sa.Column('dbytes', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('sttl', sa.Integer(), nullable=True),
    sa.Column('dttl', sa.Integer(), nullable=True),
    sa.Column('sload', sa.Float(), nullable=True),
    sa.Column('dload', sa.Float(), nullable=True),
    sa.Column('sloss', sa.Integer(), nullable=True),
    sa.Column('dloss', sa.Integer(), nullable=True),
    sa.Column('sinpkt', sa.Float(), nullable=True),
    sa.Column('dinpkt', sa.Float(), nullable=True),
    sa.Column('sjit', sa.Float(), nullable=True),
    sa.Column('djit', sa.Float(), nullable=True),
    sa.Column('swin', sa.Integer(), nullable=True),
    sa.Column('stcpb', sa.Integer(), nullable=True),
    sa.Column('dtcpb', sa.Integer(), nullable=True),
    sa.Column('dwin', sa.Integer(), nullable=True),
    sa.Column('tcprtt', sa.Float(), nullable=True),
    sa.Column('synack', sa.Float(), nullable=True),
    sa.Column('ackdat', sa.Float(), nullable=True),
    sa.Column('smean', sa.Integer(), nullable=True),
    sa.Column('dmean', sa.Integer(), nullable=True),
    sa.Column('trans_depth', sa.Integer(), nullable=True),
    sa.Column('response_body_len', sa.Integer(), nullable=True),
    sa.Column('ct_srv_src', sa.Integer(), nullable=True),
    sa.Column('ct_state_ttl', sa.Integer(), nullable=True),
    sa.Column('ct_dst_ltm', sa.Integer(), nullable=True),
    sa.Column('ct_src_dport_ltm', sa.Integer(), nullable=True),
    sa.Column('ct_dst_sport_ltm', sa.Integer(), nullable=True),
    sa.Column('ct_dst_src_ltm', sa.Integer(), nullable=True),
    sa.Column('is_ftp_login', sa.Integer(), nullable=True),
    sa.Column('ct_ftp_cmd', sa.Integer(), nullable=True),
    sa.Column('ct_flw_http_mthd', sa.Integer(), nullable=True),
    sa.Column('ct_src_ltm', sa.Integer(), nullable=True),
    sa.Column('ct_srv_dst', sa.Integer(), nullable=True),
    sa.Column('is_sm_ips_ports', sa.Integer(), nullable=True),
    sa.Column('attack_cat', sa.String(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('predicted_label', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
